# Generated by Django 6.0.5 on 2026-05-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='is_burn_after_reading',
            field=models.BooleanField(default=False),
        ),
    ]
